# Each route discribes how an incoming URL will be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "j_project:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"